Fixes possible NullPointer in ProtoType.java
Matroska-Org/jebml pull request #7
Opened 2018-09-27 15:31 UTC by simonleber

2018-09-27 16:22 UTC, mbunkus requested changes

2018-09-27 16:22 UTC, mbunkus commented on src/main/java/org/ebml/ProtoType.java
> +    if (eType == null) {
Thanks for the PR.

I don't know (nor use) the Java code, but just from looking at the surrounding lines it seems clear to me that the check has to be moved upwards, at least before the `LOG.trace…` line as that one dereferences `eType` already.

2018-10-04 13:48 UTC, simonleber commented on src/main/java/org/ebml/ProtoType.java
> +    if (eType == null) {
I moved the Nullpointer check onto the appropriate position in the code. To hide my sloppiness i amended the commit. Would u consider merging it now?

2019-11-10 20:35 UTC, SiWoC commented on src/main/java/org/ebml/ProtoType.java
> +      return null;
I would also suggest returning Void to have the rest of the file getting parsed correctly and logging the unknown codename
```suggestion
      LOG.error("Unknown codename [" + codename + "]=[" + EBMLReader.bytesToHex(type.array()) + "], returning [Void]");
      return MatroskaDocTypes.Void.getInstance();
    
```

2020-02-17 22:41 UTC, merged

2020-02-17 22:41 UTC, mbunkus commented
Thanks.